USE Amazondb;
SELECT* FROM Users;
SELECT * FROM Products;
SELECT * FROM Orders;
SELECT * FROM OrderDetails;

---- 1. List all customers who have made purchases of more than $80 ----
---- Taking Full Join ----
CREATE TABLE Users_Orders AS
SELECT
	Users.user_id AS user_id,
    Users.name,
    Orders.order_id,
    Orders.user_id AS order_user_id,
    Orders.total_amount
FROM Users
LEFT JOIN Orders
ON Users.user_id = Orders.user_id;

SELECT * FROM Users_Orders;

--- Having Clause ---
--- Fetch Purchase more than $80 ----
SELECT name, SUM(total_amount) AS Total_Purchase
FROM Users_Orders
GROUP BY name
HAVING Total_Purchase > 80;

---- 2. Retrieve all orders placed in the last 280 days along with the customer name and email ----
SELECT * FROM Users;
SELECT * FROM Products;
SELECT * FROM Orders;
SELECT * FROM OrderDetails;

SELECT 
     Users.user_id,
     Users.name,
     Users.email,
     Orders.user_id,
     Orders.order_date,
     Orders.order_id
FROM Users
JOIN Orders
ON Users.user_id = orders.user_id
AND Orders.order_date >= CURDATE() - INTERVAL 280 day;

--- 3.Find the average product price for each category. ---
SELECT * from Products;

SELECT 
	category,
	AVG(price) AS Avg_price
FROM 
	Products
GROUP BY
	category;
    
---- 4. List all customers who have purchased a product from the category Electronics.---
---- Electronics Products name ---
SELECT 
	product_name
FROM 
	Products
WHERE 
	category = 'Electronics';

SELECT DISTINCT
	U.name,
    U.email
FROM Users U
JOIN Orders O ON U.user_id = O.user_id		
JOIN OrderDetails OD ON OD.order_id = O.order_id
JOIN Products P ON P.product_id = OD.product_id
WHERE category = 'Electronics';

--- 5. Find the total number of products sold and the total revenue generated for each product.---
SELECT 
	P.product_name as Product_name,
    SUM(OD.quantity) as Total_number_of_Products_sold,
    SUM(OD.quantity * P.price) as Total_Revenue_generated
FROM Products P
JOIN OrderDetails OD ON P.product_id = OD.product_id
GROUP BY P.product_id;

--- 6.Update the price of all products in the Books category, increasing it by 10% Query---
SELECT * from Products;

SELECT
	price
FROM Products
WHERE category = 'Books';

ALTER TABLE Products
MODIFY price DECIMAL(10,5);

SET SQL_SAFE_UPDATES = 0;

TRUNCATE TABLE Products;

UPDATE 
	Products
SET 
	price = price * 1.10
WHERE category = 'Books';

SELECT * FROM Products;

---- 7.Remove all orders that were placed before 2020 ---

UPDATE Orders
SET order_date = '2019-02-02'
WHERE user_id = 3;

SELECT * from Orders;

DELETE FROM
	Orders
WHERE 
	order_date < '2019-02-02';
    
------ 8. Write a query to fetch the order details, including customer name, product name, and quantity, for orders placed on 2024-05-01---
SELECT * FROM Users;
SELECT * FROM Products;
SELECT * FROM OrderDetails;
SELECT * FROM Orders;

SELECT
	U.name as Customer_name,
    P.product_name,
    OD.quantity,
    O.order_id,
    O.order_date
FROM Users U
JOIN Orders O ON O.user_id = U.user_id
JOIN OrderDetails OD ON OD.order_id = O.order_id
JOIN Products P ON P.product_id = OD.product_id
WHERE order_date = '2024-05-01';

--- 9.Fetch all customers and the total number of orders they have placed.---
SELECT
	U.name as Customer_name,
    U.email,
    COUNT(O.order_id) as Total_orders
FROM Users U
LEFT JOIN Orders O
ON U.user_id = O.user_id 
GROUP BY U.user_id;

--- List all customers who purchased more than 1 units of any product, including the product name and total quantity purchased.---
SELECT 
	U.name as Customer_name,
    P.product_name,
    SUM(OD.quantity) as Total_quantity 
FROM Users U
JOIN Orders O ON U.user_id = O.user_id
JOIN OrderDetails OD ON OD.order_id = O.order_id
JOIN Products P ON P.product_id = OD.product_id
GROUP BY U.name, P.product_name;

---- 11. Find the total revenue generated by each category along with the category name.----
SELECT
	P.category,
    SUM(OD.quantity * P.price) as Total_revenue
FROM Products P
JOIN OrderDetails OD ON OD.product_id = P.product_id
GROUP BY P.category;    

